// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateReservationForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2 id=\"titulo-h2\" class=\"titulo-h2\">Nueva reserva</h2><form id=\"form-crear-reserva\" class=\"form-crear-reserva\" hx-post=\"/reservations\" hx-target=\"#reservation-list-container\" hx-swap=\"outerHTML\" hx-on::after-request=\"this.reset()\"><div class=\"form-control\"><label for=\"new-cabin-id\">Cabin ID</label> <input type=\"number\" id=\"new-cabin-id\" name=\"cabin_id\" placeholder=\"Cabin ID\" required></div><div class=\"form-control\"><label for=\"new-fecha\">Fecha</label> <input type=\"date\" id=\"new-fecha\" name=\"fecha\" required></div><div class=\"form-control\"><label class=\"label-fantasma\">&nbsp;</label> <button type=\"submit\">Crear</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UpdateReservationForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h2 id=\"titulo-h2\" class=\"titulo-h2\">Actualizar reserva</h2><form id=\"form-actualizar-reserva\" class=\"form-actualizar-reserva\" hx-post=\"/reservations/update\" hx-target=\"#reservation-list-container\" hx-swap=\"outerHTML\" hx-on::after-request=\"this.reset()\"><div class=\"form-control\"><label for=\"update-cabin-id\">Cabin ID</label> <input type=\"number\" id=\"update-cabin-id\" name=\"cabin_id\" placeholder=\"Cabin ID\" required></div><div class=\"form-control\"><label for=\"fecha-actual\">Fecha actual de la reserva</label> <input type=\"date\" id=\"fecha-actual\" name=\"fecha\" required></div><div class=\"form-control\"><label for=\"fecha-nueva\">Nueva fecha</label> <input type=\"date\" id=\"fecha-nueva\" name=\"fecha_nueva\" required></div><div class=\"form-control\"><label class=\"label-fantasma\">&nbsp;</label> <button type=\"submit\">Actualizar</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
