// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Cabin struct {
	ID           int32     `json:"id"`
	EmailContact string    `json:"email_contact"`
	PhoneContact string    `json:"phone_contact"`
	Password     string    `json:"password"`
	CreatedAt    time.Time `json:"created_at"`
}

type Reservation struct {
	ID        int32     `json:"id"`
	CabinID   int32     `json:"cabin_id"`
	Fecha     time.Time `json:"fecha"`
	CreatedAt time.Time `json:"created_at"`
}
